use_gpu: True
device: 3
seed: 0
framework: 'InsGNN'
data:
  root: 'data/'
  data_name: 'spmotif_0.7'
  loader_size: 128
  splitter: 'rand'   #choices=['rand','fold10']
  data_split_ratio: 0.7
  fold_idx: 0  #'the index(<10) of fold in 10-fold validation.')
  shuffle: False
  one_hot: False
  ts_length: 921600
  mutag_x: False

  splits:
    train: 0.8
    valid: 0.1
    test: 0.1

sampling:
  hz: 128
  samplingFlag: True
  normalizeFlag: True
  step: 2
  ValueError_interrupt: True

model:
  type: 'PNA'
  data_batch_size: 3
  target_class: 2
  out_channels: 7
  model_save_path: 'result/model/'
  num_layers: 3
  num_mlp_layers: 2
  hidden_size: 80
  n_layers: 4
  dropout_p: 0.3
  pretrain_lr: 3.0e-3
  pretrain_epochs: 100

  from_scratch: True
  fix_r: False
  decay_interval: 60
  decay_r: 0.1
  final_r: 0.7

  normal_coef: 0.0
  kl_1_coef: 1.0
  kl_2_coef: 1.0
  GC_coef: 1.0
  GC_delta_coef: 1.0
  aggregators:
    - mean
    - min
    - max
    - std
    - sum


timeseries:
  shapelet: True
  epochs: 50
  shaplet_method: 'shapelets_Its'
  K: 5
  R: 2
  alpha: 0.01
  lamda: 0.01
  eta: 0.001
  shapelet_initialization: 'segments_centroids'
  patience: 20
  shaplet_outsize: 30
  shaplet_segment: 4


train:
  lr: 3.0e-3
  weight_decay: 3.0e-6
  graph_lr: 3.0e-3
  optimizer: "Adam"
  final_dropout: 0.7
  learn_eps: "store_true"
  epochs: 150

shared_config:
  learn_edge_att: true
  learn_edge_att_m: true
  precision_k: 5
  num_viz_samples: 0
  viz_interval: 10
  viz_norm_att: true
  extractor_dropout_p: 0.5

visual:
  num_viz_samples: 10

#GSAT_config:
#  method_name: 'GSAT'
#  pred_loss_coef: 1
#  info_loss_coef: 1
#  epochs: 200
#  lr: 3.0e-3
#  weight_decay: 3.0e-6
#
#  from_scratch: true
#  fix_r: false
#  decay_interval: 60
#  decay_r: 0.1
#  final_r: 0.7

resultPath: 'result/'
